[package]
name = "jq-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde_json = { version ="1.0.132", features = ["preserve_order"] }
thiserror = "1.0.64"
